import collections

try:
    tachyon = open("inputs/day07.txt").read()
except FileNotFoundError:
    tachyon = """
.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
"""[1:]
tachyon = tachyon.splitlines()

index = tachyon[0].index("S")
splits = collections.Counter([index])

split_count = 0
for x in tachyon[1:]:
    new_splits = collections.Counter()
    for split, count in splits.items():
        if x[split] == "^":
            new_splits[split - 1] += count
            new_splits[split + 1] += count
            split_count += 1
        else:
            new_splits[split] += count
    splits = new_splits

print("answer 1:", split_count)
print("answer 2:", sum(splits.values()))
